---
namespace: javielico
name: mac
version: "0.0.2"
readme: README.md

authors:
  - javielico

description: Collection of macOS automation tools for Ansible.

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
license:
  - gnu

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags:
  - mac
  - macos
  - osx
  - homebrew
  - brew
  - workstation
  - dev
  - mas
  - appstore
  - apps
  - configure
  - development
  - apple
  - macbook
  - imac
  - macmini
  - server

dependencies:
  community.general: ">=3.0.0"

repository: https://github.com/javielico/mac-ansible-galaxy
documentation: https://github.com/javielico/mac-ansible-galaxy
homepage: https://github.com/javielico/
issues: https://github.com/javielico/mac-ansible-galaxy/issues

build_ignore: []
